  version: '3'

  services:
    node-service:
      image: node:18
      build: .
      working_dir: /app
      volumes:
        - .:/app
      ports:
        - "3000:3000"
      command: ["node", "server.js"]
